apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: statics-web
    newName: ghcr.io/fdshg693/statics-web
    newTag: dev
  - name: statics-htmx-sugoroku-api
    newName: ghcr.io/fdshg693/statics-htmx-sugoroku-api
    newTag: dev
