apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: statics-web
    newTag: local
  - name: statics-htmx-sugoroku-api
    newTag: local

replicas:
  - name: caddy-static
    count: 1
  - name: htmx-sugoroku-api
    count: 1
