apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: statics
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy-static
                port:
                  number: 80
