apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: statics

resources:
  - namespace.yaml
  - caddy-static-deployment.yaml
  - caddy-static-service.yaml
  - htmx-sugoroku-api-deployment.yaml
  - htmx-sugoroku-api-service.yaml
  - ingress.yaml

images:
  - name: statics-web
    newTag: dev
  - name: statics-htmx-sugoroku-api
    newTag: dev
